ALTER TABLE purchase_invoices
ADD COLUMN IF NOT EXISTS currency_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS payment_terms_code VARCHAR(50),
ADD COLUMN IF NOT EXISTS remarks TEXT,
ADD COLUMN IF NOT EXISTS total_discount_amount NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_tax_amount NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS amount_including_tax NUMERIC(18,2) DEFAULT 0;

ALTER TABLE posted_purchase_invoices
ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'Posted',
ADD COLUMN IF NOT EXISTS remarks TEXT,
ADD COLUMN IF NOT EXISTS currency_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS payment_terms_code VARCHAR(50),
ADD COLUMN IF NOT EXISTS total_discount_amount NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_tax_amount NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS amount_including_tax NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS posted_by VARCHAR(100);

ALTER TABLE purchase_invoice_lines
ADD COLUMN IF NOT EXISTS line_discount_amount NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_pct NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS amount_including_tax NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS hsn_sac_code VARCHAR(50);

ALTER TABLE posted_purchase_invoice_lines
ADD COLUMN IF NOT EXISTS line_discount_amount NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_pct NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS amount_including_tax NUMERIC(18,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS hsn_sac_code VARCHAR(50);

ALTER TABLE posted_purchase_receipt_lines
ADD COLUMN IF NOT EXISTS quantity_invoiced NUMERIC(18,2) DEFAULT 0;
