ALTER TABLE purchase_invoices
  ADD COLUMN IF NOT EXISTS tds_pct NUMERIC(18,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS surcharge_pct NUMERIC(18,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cess_pct NUMERIC(18,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_tds_pct NUMERIC(18,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS previous_tds_base_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_tds_base_amount NUMERIC(18,2) DEFAULT 0;

ALTER TABLE posted_purchase_invoices
  ADD COLUMN IF NOT EXISTS tds_pct NUMERIC(18,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS surcharge_pct NUMERIC(18,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cess_pct NUMERIC(18,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_tds_pct NUMERIC(18,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS previous_tds_base_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_tds_base_amount NUMERIC(18,2) DEFAULT 0;
