ALTER TABLE sales_orders
  ADD COLUMN IF NOT EXISTS customer_gst_reg_no varchar(50),
  ADD COLUMN IF NOT EXISTS gst_customer_type varchar(50),
  ADD COLUMN IF NOT EXISTS salesperson_code varchar(50),
  ADD COLUMN IF NOT EXISTS location_code varchar(50),
  ADD COLUMN IF NOT EXISTS external_document_no varchar(100),
  ADD COLUMN IF NOT EXISTS your_reference varchar(100),
  ADD COLUMN IF NOT EXISTS discount numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS narration text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS address_2 text,
  ADD COLUMN IF NOT EXISTS city varchar(100),
  ADD COLUMN IF NOT EXISTS post_code varchar(30),
  ADD COLUMN IF NOT EXISTS country_region_code varchar(50),
  ADD COLUMN IF NOT EXISTS contact varchar(100),
  ADD COLUMN IF NOT EXISTS email varchar(150),
  ADD COLUMN IF NOT EXISTS phone_no varchar(50),
  ADD COLUMN IF NOT EXISTS ship_to_code varchar(50),
  ADD COLUMN IF NOT EXISTS ship_to_name varchar(150),
  ADD COLUMN IF NOT EXISTS ship_to_address text,
  ADD COLUMN IF NOT EXISTS ship_to_city varchar(100),
  ADD COLUMN IF NOT EXISTS due_date date,
  ADD COLUMN IF NOT EXISTS shipment_date date,
  ADD COLUMN IF NOT EXISTS requested_delivery_date date,
  ADD COLUMN IF NOT EXISTS promised_delivery_date date,
  ADD COLUMN IF NOT EXISTS currency_code varchar(20),
  ADD COLUMN IF NOT EXISTS payment_terms_code varchar(50),
  ADD COLUMN IF NOT EXISTS payment_method_code varchar(50),
  ADD COLUMN IF NOT EXISTS shipment_method_code varchar(50);

ALTER TABLE sales_order_lines
  ADD COLUMN IF NOT EXISTS qty_to_ship numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS qty_shipped numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hsn_sac_code varchar(50);
