ALTER TABLE vendor_ledger_entries
ADD COLUMN IF NOT EXISTS gross_invoice_amount NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tds_amount NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS net_payable_amount NUMERIC(12,2) DEFAULT 0;
