ALTER TABLE purchase_invoices
  ADD COLUMN IF NOT EXISTS subtotal_excl_vat NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_gst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_excl_vat NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_vat NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_incl_vat NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invoice_discount_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invoice_discount_pct NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tds_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS change_tds BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS tds_less_amount NUMERIC(18,2) DEFAULT 0;

ALTER TABLE posted_purchase_invoices
  ADD COLUMN IF NOT EXISTS subtotal_excl_vat NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_gst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_excl_vat NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_vat NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_incl_vat NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invoice_discount_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invoice_discount_pct NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tds_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS change_tds BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS tds_less_amount NUMERIC(18,2) DEFAULT 0;

ALTER TABLE purchase_invoice_lines
  ADD COLUMN IF NOT EXISTS gst_group_code VARCHAR(50),
  ADD COLUMN IF NOT EXISTS gst_calculation_type VARCHAR(30),
  ADD COLUMN IF NOT EXISTS cgst_pct NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst_pct NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst_pct NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_gst_pct NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_gst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS taxable_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount_including_gst NUMERIC(18,2) DEFAULT 0;

ALTER TABLE posted_purchase_invoice_lines
  ADD COLUMN IF NOT EXISTS gst_group_code VARCHAR(50),
  ADD COLUMN IF NOT EXISTS gst_calculation_type VARCHAR(30),
  ADD COLUMN IF NOT EXISTS cgst_pct NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst_pct NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst_pct NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_gst_pct NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_gst_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS taxable_amount NUMERIC(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount_including_gst NUMERIC(18,2) DEFAULT 0;
