ALTER TABLE items
  ADD COLUMN IF NOT EXISTS is_by_product boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS by_product_cost numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_date_modified date,
  ADD COLUMN IF NOT EXISTS gtin varchar(100),
  ADD COLUMN IF NOT EXISTS common_item_no varchar(100),
  ADD COLUMN IF NOT EXISTS purchasing_code varchar(100),
  ADD COLUMN IF NOT EXISTS purchase_tolerance_pct numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sales_tolerance_pct numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS variant_mandatory_if_exists varchar(100),
  ADD COLUMN IF NOT EXISTS shelf_no varchar(100),
  ADD COLUMN IF NOT EXISTS created_from_catalog_item boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS qty_on_prod_order numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS qty_on_component_lines numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS qty_on_project_order numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS qty_on_asm_component numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS over_receipt_code varchar(100),
  ADD COLUMN IF NOT EXISTS last_direct_cost numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS net_invoiced_qty numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cost_is_adjusted boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS cost_is_posted_to_gl boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS default_deferral_template varchar(100),
  ADD COLUMN IF NOT EXISTS hsn_sac_code varchar(100),
  ADD COLUMN IF NOT EXISTS exempted boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS subcontracting boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS sub_comp_location varchar(100),
  ADD COLUMN IF NOT EXISTS subscription_option varchar(100),
  ADD COLUMN IF NOT EXISTS lead_time_calculation varchar(100),
  ADD COLUMN IF NOT EXISTS production_bom_no varchar(100),
  ADD COLUMN IF NOT EXISTS routing_no varchar(100),
  ADD COLUMN IF NOT EXISTS rounding_precision numeric DEFAULT 1,
  ADD COLUMN IF NOT EXISTS flushing_method varchar(100),
  ADD COLUMN IF NOT EXISTS scrap_pct numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lot_size numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS production_blocked varchar(100),
  ADD COLUMN IF NOT EXISTS assembly_policy varchar(100),
  ADD COLUMN IF NOT EXISTS assembly_bom varchar(100),
  ADD COLUMN IF NOT EXISTS reordering_policy varchar(100),
  ADD COLUMN IF NOT EXISTS order_tracking_policy varchar(100),
  ADD COLUMN IF NOT EXISTS safety_lead_time varchar(100),
  ADD COLUMN IF NOT EXISTS include_inventory boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS lot_accumulation_period varchar(100),
  ADD COLUMN IF NOT EXISTS rescheduling_period varchar(100),
  ADD COLUMN IF NOT EXISTS item_tracking_code varchar(100),
  ADD COLUMN IF NOT EXISTS serial_nos varchar(100),
  ADD COLUMN IF NOT EXISTS lot_nos varchar(100),
  ADD COLUMN IF NOT EXISTS expiration_calculation varchar(100),
  ADD COLUMN IF NOT EXISTS warehouse_class_code varchar(100),
  ADD COLUMN IF NOT EXISTS put_away_template_code varchar(100),
  ADD COLUMN IF NOT EXISTS put_away_unit_of_measure_code varchar(100),
  ADD COLUMN IF NOT EXISTS phys_invt_counting_period_code varchar(100),
  ADD COLUMN IF NOT EXISTS last_phys_invt_date date,
  ADD COLUMN IF NOT EXISTS last_counting_period_update date,
  ADD COLUMN IF NOT EXISTS next_counting_start_date date,
  ADD COLUMN IF NOT EXISTS next_counting_end_date date;
