ALTER TABLE mandi_vendor
  ADD COLUMN IF NOT EXISTS search_name varchar(255),
  ADD COLUMN IF NOT EXISTS address_2 text,
  ADD COLUMN IF NOT EXISTS state_code varchar(50),
  ADD COLUMN IF NOT EXISTS country_region_code varchar(50),
  ADD COLUMN IF NOT EXISTS post_code varchar(50),
  ADD COLUMN IF NOT EXISTS mobile_phone_no varchar(50),
  ADD COLUMN IF NOT EXISTS contact_person varchar(255),
  ADD COLUMN IF NOT EXISTS purchaser_code varchar(100),
  ADD COLUMN IF NOT EXISTS responsibility_center varchar(100),
  ADD COLUMN IF NOT EXISTS location_code varchar(100),
  ADD COLUMN IF NOT EXISTS payment_terms_code varchar(100),
  ADD COLUMN IF NOT EXISTS payment_method_code varchar(100),
  ADD COLUMN IF NOT EXISTS shipment_method_code varchar(100),
  ADD COLUMN IF NOT EXISTS gst_registration_no varchar(100),
  ADD COLUMN IF NOT EXISTS gst_vendor_type varchar(100),
  ADD COLUMN IF NOT EXISTS pan_no varchar(100),
  ADD COLUMN IF NOT EXISTS pan_status varchar(100),
  ADD COLUMN IF NOT EXISTS pan_reference_no varchar(100),
  ADD COLUMN IF NOT EXISTS msme boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS msme_no varchar(100),
  ADD COLUMN IF NOT EXISTS subcontractor boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS transporter boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS bank_name varchar(255),
  ADD COLUMN IF NOT EXISTS bank_account_no varchar(100),
  ADD COLUMN IF NOT EXISTS ifsc_code varchar(100),
  ADD COLUMN IF NOT EXISTS balance_lcy numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS balance_due_lcy numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS payments_lcy numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS blocked boolean DEFAULT false;
