import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Boxes,
  ClipboardCheck,
  FileText,
  Factory,
  Gauge,
  Hash,
  Landmark,
  ListOrdered,
  MapPin,
  Package,
  Percent,
  Receipt,
  Ruler,
  Send,
  Settings,
  ShoppingBag,
  ShoppingCart,
  Truck,
  Users,
  Warehouse,
} from "lucide-react";

export type NavigationSection = "Operations" | "Masters" | "Setup";

export type NavigationItem = {
  title: string;
  path: string;
  category: string;
  section: NavigationSection;
  keywords: string[];
  icon: LucideIcon;
  showInSidebar?: boolean;
  hiddenFromSidebar?: boolean;
  searchable?: boolean;
};

export const navigationItems: NavigationItem[] = [
  {
    title: "Dashboard",
    path: "/",
    category: "Home",
    section: "Operations",
    keywords: ["dashboard", "home", "overview", "activity"],
    icon: Gauge,
  },
  {
    title: "Customers",
    path: "/customers",
    category: "Masters",
    section: "Masters",
    keywords: ["customer", "customer master", "customer nos", "receivables"],
    icon: Users,
  },
  {
    title: "Vendors",
    path: "/vendors",
    category: "Masters",
    section: "Masters",
    keywords: ["vendor", "vendor master", "vendor nos", "payables"],
    icon: Warehouse,
  },
  {
    title: "Mandi Vendors",
    path: "/mandi-vendor",
    category: "Masters",
    section: "Masters",
    keywords: ["mandi vendor", "mandi vendor master", "broker vendor"],
    icon: Warehouse,
  },
  {
    title: "Items",
    path: "/items",
    category: "Inventory",
    section: "Masters",
    keywords: ["item", "item master", "item card", "item nos"],
    icon: Package,
  },
  {
    title: "Item Variants",
    path: "/item-variants",
    category: "Inventory",
    section: "Masters",
    keywords: ["item variants", "variant", "variant code", "item card variants"],
    icon: Boxes,
  },
  {
    title: "Item Categories",
    path: "/item-categories",
    category: "Inventory",
    section: "Masters",
    keywords: [
      "item categories",
      "item category",
      "category hierarchy",
      "raw material category",
      "finished goods category",
      "classification",
      "attributes",
    ],
    icon: Package,
    showInSidebar: false,
    hiddenFromSidebar: true,
    searchable: true,
  },
  {
    title: "Families",
    path: "/families",
    category: "Inventory",
    section: "Masters",
    keywords: [
      "families",
      "family",
      "family card",
      "item family",
      "item classification",
      "item category family",
      "biscuit family",
      "finished goods family",
    ],
    icon: Boxes,
    showInSidebar: false,
    hiddenFromSidebar: true,
    searchable: true,
  },
  {
    title: "Currencies",
    path: "/currencies",
    category: "Setup",
    section: "Setup",
    keywords: [
      "currencies",
      "currency",
      "currency card",
      "currency exchange rates",
      "exchange rates",
      "iso currency",
      "inr",
      "usd",
      "aed",
    ],
    icon: Landmark,
    showInSidebar: false,
    hiddenFromSidebar: true,
    searchable: true,
  },
  {
    title: "Salespeople/Purchasers",
    path: "/salespeople-purchasers",
    category: "Masters",
    section: "Masters",
    keywords: [
      "salespeople",
      "salesperson",
      "purchasers",
      "purchaser",
      "salesperson purchaser",
      "salesperson card",
      "purchaser card",
      "commission",
      "department code",
      "customer group",
    ],
    icon: Users,
    showInSidebar: false,
    hiddenFromSidebar: true,
    searchable: true,
  },
  {
    title: "Locations",
    path: "/locations",
    category: "Inventory",
    section: "Masters",
    keywords: ["location", "location master", "location nos", "warehouse"],
    icon: MapPin,
  },
  {
    title: "Unit of Measure",
    path: "/unit-of-measure",
    category: "Inventory",
    section: "Masters",
    keywords: ["unit of measure", "uom", "base uom", "purchase uom", "sales uom"],
    icon: Ruler,
  },
  {
    title: "Mandi Master",
    path: "/mandi-master",
    category: "Masters",
    section: "Masters",
    keywords: ["mandi master", "mandi setup", "mandi item", "mandi vendor mapping"],
    icon: ShoppingBag,
  },
  {
    title: "Mandi Purchase",
    path: "/mandi-purchase",
    category: "Purchase",
    section: "Operations",
    keywords: ["mandi purchase", "purchase procurement", "mp"],
    icon: ListOrdered,
  },
  {
    title: "Purchase Orders",
    path: "/purchase-orders",
    category: "Purchase",
    section: "Operations",
    keywords: ["purchase order", "po", "purchase document"],
    icon: FileText,
  },
  {
    title: "Inward Gate Entries",
    path: "/inward-gate-entries",
    category: "Purchase",
    section: "Operations",
    keywords: ["inward gate entry", "gate entry", "ige", "material gate"],
    icon: Truck,
  },
  {
    title: "Goods Receipt Notes",
    path: "/goods-receipt-notes",
    category: "Purchase",
    section: "Operations",
    keywords: ["goods receipt note", "grn", "receipt note"],
    icon: Receipt,
  },
  {
    title: "Posted Purchase Receipts",
    path: "/posted-purchase-receipts",
    category: "Purchase",
    section: "Operations",
    keywords: ["posted purchase receipt", "purchase receipt", "ppr"],
    icon: ClipboardCheck,
  },
  {
    title: "Purchase Invoices",
    path: "/purchase-invoices",
    category: "Purchase",
    section: "Operations",
    keywords: ["purchase invoice", "purchase invoice nos", "pi", "vendor invoice"],
    icon: FileText,
  },
  {
    title: "Posted Purchase Invoices",
    path: "/posted-purchase-invoices",
    category: "Purchase",
    section: "Operations",
    keywords: ["posted purchase invoice", "posted purchase invoice nos", "ppi"],
    icon: ClipboardCheck,
  },
  {
    title: "Sales Orders",
    path: "/sales-orders",
    category: "Sales",
    section: "Operations",
    keywords: ["sales order", "so", "sales document"],
    icon: ShoppingCart,
  },
  {
    title: "Posted Sales Shipments",
    path: "/posted-sales-shipments",
    category: "Sales",
    section: "Operations",
    keywords: ["posted sales shipment", "sales shipment", "shipment", "pss"],
    icon: Send,
  },
  {
    title: "Sales Invoices",
    path: "/sales-invoices",
    category: "Sales",
    section: "Operations",
    keywords: ["sales invoice", "sales invoice nos", "si", "customer invoice"],
    icon: FileText,
  },
  {
    title: "Posted Sales Invoices",
    path: "/posted-sales-invoices",
    category: "Sales",
    section: "Operations",
    keywords: ["posted sales invoice", "posted sales invoice nos", "psi"],
    icon: ClipboardCheck,
  },
  {
    title: "Item Ledger Entries",
    path: "/item-ledger-entries",
    category: "Inventory",
    section: "Operations",
    keywords: ["item ledger entries", "ledger", "inventory ledger", "item movement"],
    icon: BookOpen,
  },
  {
    title: "Reversal Entries",
    path: "/reversal-entries",
    category: "Inventory",
    section: "Operations",
    keywords: [
      "reversal entries",
      "reversal entry",
      "undo shipment",
      "undo receipt",
      "sales shipment reversal",
      "purchase receipt reversal",
      "posted document reversal",
      "inventory reversal",
      "audit trail",
    ],
    icon: BookOpen,
    showInSidebar: false,
    hiddenFromSidebar: true,
    searchable: true,
  },
  {
    title: "Vendor Ledger Entries",
    path: "/vendor-ledger-entries",
    category: "Purchase",
    section: "Operations",
    keywords: ["vendor ledger", "vendor ledger entries", "payables ledger", "purchase payable", "posted purchase invoice balance"],
    icon: BookOpen,
    showInSidebar: false,
  },
  {
    title: "Customer Ledger Entries",
    path: "/customer-ledger-entries",
    category: "Sales",
    section: "Operations",
    keywords: ["customer ledger", "customer ledger entries", "receivables ledger", "sales receivable", "posted sales invoice balance"],
    icon: BookOpen,
    showInSidebar: false,
  },
  {
    title: "No. Series",
    path: "/no-series",
    category: "Setup",
    section: "Operations",
    keywords: ["series", "number series", "nos", "document numbering", "no series lines"],
    icon: Hash,
  },
  {
    title: "GST Groups",
    path: "/gst-groups",
    category: "Setup",
    section: "Setup",
    keywords: ["gst", "tax", "gst setup", "gst group", "gst groups", "cgst", "sgst", "igst"],
    icon: Percent,
    showInSidebar: false,
  },
  {
    title: "GST Rates",
    path: "/gst-rates",
    category: "Setup",
    section: "Setup",
    keywords: ["gst", "tax", "rates", "gst rates", "gst setup", "gst group", "cgst", "sgst", "igst"],
    icon: Percent,
    showInSidebar: false,
  },
  {
    title: "GST Setup",
    path: "/gst-setup",
    category: "Setup",
    section: "Setup",
    keywords: ["gst", "gst setup", "gst tax type", "cess tax type", "e-invoice", "gst rates", "gst groups"],
    icon: Percent,
    showInSidebar: false,
  },
  {
    title: "TDS Setup",
    path: "/tds-setup",
    category: "Setup",
    section: "Setup",
    keywords: ["tds", "tax deducted at source", "tds setup", "nil challan", "remittance"],
    icon: Percent,
    showInSidebar: false,
  },
  {
    title: "TDS Sections",
    path: "/tds-sections",
    category: "Setup",
    section: "Setup",
    keywords: ["tds", "tds section", "tds sections", "section code", "194c", "194j", "194i", "194q", "195"],
    icon: Percent,
    showInSidebar: false,
  },
  {
    title: "TDS Rates",
    path: "/tds-rates",
    category: "Setup",
    section: "Setup",
    keywords: ["tds", "tds rates", "tax deducted at source", "tds setup", "assessee code", "194c", "194j", "194i", "194q", "195"],
    icon: Percent,
    showInSidebar: false,
  },
  {
    title: "Section Codes",
    path: "/tds-section-codes",
    category: "Setup",
    section: "Setup",
    keywords: ["tds", "section code", "section codes", "tds section", "194c", "194j", "194i", "194q", "195"],
    icon: Percent,
    showInSidebar: false,
  },
  {
    title: "Assessee Codes",
    path: "/tds-assessee-codes",
    category: "Setup",
    section: "Setup",
    keywords: ["tds", "assessee code", "assessee codes", "individual", "huf", "company", "nri", "tax deducted at source"],
    icon: Users,
    showInSidebar: false,
  },
  {
    title: "States",
    path: "/states",
    category: "Setup",
    section: "Setup",
    keywords: [
      "states",
      "state master",
      "state code",
      "gst state code",
      "gst reg no state code",
      "etds",
      "tcs",
      "tds state",
      "india localization",
    ],
    icon: MapPin,
    showInSidebar: false,
    hiddenFromSidebar: true,
    searchable: true,
  },
  {
    title: "Manufacturing Setup",
    path: "/manufacturing-setup",
    category: "Manufacturing",
    section: "Setup",
    keywords: ["manufacturing", "manufacturing setup", "released production order nos", "consumption journal", "output journal", "routing"],
    icon: Factory,
    showInSidebar: false,
  },
  {
    title: "Production BOMs",
    path: "/production-boms",
    category: "Manufacturing",
    section: "Operations",
    keywords: ["manufacturing", "production bom", "certified bom", "finished goods", "raw material", "bom"],
    icon: Factory,
    showInSidebar: false,
  },
  {
    title: "Released Production Orders",
    path: "/released-production-orders",
    category: "Manufacturing",
    section: "Operations",
    keywords: ["manufacturing", "released production order", "production order", "finished goods", "refresh production order", "routing"],
    icon: Factory,
    showInSidebar: false,
  },
  {
    title: "Consumption Journal",
    path: "/consumption-journal",
    category: "Manufacturing",
    section: "Operations",
    keywords: ["manufacturing", "consumption journal", "raw material", "production consumption", "bom"],
    icon: Factory,
    showInSidebar: false,
  },
  {
    title: "Output Journal",
    path: "/output-journal",
    category: "Manufacturing",
    section: "Operations",
    keywords: ["manufacturing", "output journal", "finished goods", "production output", "bom"],
    icon: Factory,
    showInSidebar: false,
  },
  {
    title: "Item Journal",
    path: "/item-journal",
    category: "Inventory",
    section: "Operations",
    keywords: ["item journal", "item journals", "inventory journal", "positive adjustment", "raw material stock", "manufacturing inventory"],
    icon: Package,
    showInSidebar: false,
  },
  {
    title: "Assembly BOM",
    path: "/assembly-bom",
    category: "Manufacturing",
    section: "Operations",
    keywords: ["assembly", "assembly bom", "assembly item", "component item", "bom", "business central"],
    icon: Factory,
    showInSidebar: false,
  },
  {
    title: "Assembly Orders",
    path: "/assembly-orders",
    category: "Manufacturing",
    section: "Operations",
    keywords: ["assembly", "assembly order", "assemble to order", "post assembly", "finished goods"],
    icon: Factory,
    showInSidebar: false,
  },
  {
    title: "Posted Assembly Orders",
    path: "/posted-assembly-orders",
    category: "Manufacturing",
    section: "Operations",
    keywords: ["assembly", "posted assembly order", "posted assembly", "assembly output", "assembly consumption"],
    icon: Factory,
    showInSidebar: false,
  },
  {
    title: "Sales & Receivables Setup",
    path: "/setup/sales",
    category: "Setup",
    section: "Setup",
    keywords: ["setup", "sales setup", "receivables setup", "customer nos", "sales invoice nos", "posted sales invoice nos"],
    icon: ShoppingBag,
  },
  {
    title: "Purchase & Payables Setup",
    path: "/setup/purchase",
    category: "Setup",
    section: "Setup",
    keywords: ["setup", "purchase setup", "payables setup", "vendor nos", "purchase invoice nos", "posted purchase invoice nos"],
    icon: Package,
  },
  {
    title: "Inventory Setup",
    path: "/setup/inventory",
    category: "Setup",
    section: "Setup",
    keywords: ["setup", "inventory setup", "item nos", "location nos", "inventory defaults"],
    icon: Settings,
  },
];

export const sidebarSections: Array<{ title: NavigationSection; items: NavigationItem[] }> = [
  {
    title: "Operations",
    items: navigationItems.filter((item) => item.section === "Operations" && item.showInSidebar !== false),
  },
  {
    title: "Setup",
    items: navigationItems.filter((item) => item.section === "Setup" && item.showInSidebar !== false),
  },
];
